FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["CustomerApp.csproj", "./"]
RUN dotnet restore "./CustomerApp.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "CustomerApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CustomerApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 80
# Set the environment variable
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "CustomerApp.dll"]