mssql:
  enabled: true
  image: mcr.microsoft.com/mssql/server:2019-latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.2"
    limits:
      memory: "512Mi"
      cpu: "1"
  secret:
    saPassword: "RGVmYXVsdEAxMjQ1" # Base64 encoded
