apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: {{ .Values.mssql.image }}
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: MSSQL_PID
              value: "Express"
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: mssql-data
          resources:
            {{ toYaml .Values.mssql.resources | nindent 12 }}
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-data
