apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SA_PASSWORD: {{ .Values.mssql.secret.saPassword }} # Base64 encoded password (example: "Default@1245")