apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    app: mssql