apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customerapp-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: customerapp
  endpoints:
    - port: "80"
