apiVersion: v1
kind: Service
metadata:
  name: customerapp-service
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: customerapp
