apiVersion: v1
kind: Namespace
metadata:
  name: customer-space
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "customerapp"
    meta.helm.sh/release-namespace: "default"
