app:
  image: docker.io/skanveri/customerapp:latest
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.2"
    limits:
      memory: "512Mi"
      cpu: "1"

name: customerapp
namespace: customerapp-space
env: api
tls:
  secretName: customerapp-tls
  crtFile: certs/customerapp.local.crt
  keyFile: certs/customerapp.local.key
