apiVersion: v2
name: application-chart
description: A Helm chart for Kubernetes with SQL Server and .NET application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: "45.0.1"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: mssql-chart
    version: 0.1.0
    repository: file://charts/sqlserver
  - name: customerapp-chart
    version: 0.1.0
    repository: file://charts/app
